- name: Deploy a container podman
  hosts: azure_vm
  remote_user: "{{ ssh_user }}"
  become: true
  vars_files:
    - vars.yml
  tasks:
  
    - name: Pull an image "docker.io/httpd:latest"
      containers.podman.podman_image:
        name: docker.io/library/httpd
        
    - name: Taggear la imagen
      shell: podman tag httpd {{ acr_server_registry }}/public/httpd:casopractico2

    - name: Login to registry "{{ acr_username }}"
      containers.podman.podman_login:
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"
        registry: "{{ acr_server_registry }}"

    - name: Push an image "{{ acr_server_registry }}/public/httpd:casopractico2"
      containers.podman.podman_image:
        push: true
        name: "{{ acr_server_registry }}/public/httpd:casopractico2"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"

    - name: Pull an image "{{ acr_server_registry }}/public/httpd:casopractico2"
      containers.podman.podman_image:
        pull: true
        name: "{{ acr_server_registry }}/public/httpd"
        tag: "casopractico2"
        
    - name: Create a container with status strated
      containers.podman.podman_container:
        name: container
        image: "{{ acr_server_registry }}/public/httpd:casopractico2"
        state: started
        ports:
          - "80:80"
        