- name: Install PODMAN
  hosts: azure_vm
  remote_user: irene
  become: true
  tasks:       
    - name: Install Podman
      become: yes
      ansible.builtin.package:
        name: podman
        state: present
        update_cache: true