- name: Pull and push an httpd and myqsl images in the Azure registry
  hosts: azure_vm
  remote_user: "{{ ssh_user }}"
  become: true
  vars_files:
    - vars.yml
  tasks:

    - name: Pull an image "docker.io/httpd:latest"
      containers.podman.podman_image:
        name: docker.io/library/httpd
        
    - name: Pull an image "docker.io/mysql:latest"
      containers.podman.podman_image:
        name: docker.io/library/mysql
        
    - name: Tag the image "docker.io/httpd:latest"
      shell: podman tag httpd {{ acr_server_registry }}/cp2/httpd:{{ tag_image }}
        
    - name: Tag the image "docker.io/mysql:latest"
      shell: podman tag mysql {{ acr_server_registry }}/cp2/mysql:{{ tag_image }}

    - name: Login to registry "{{ acr_username }}"
      containers.podman.podman_login:
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"
        registry: "{{ acr_server_registry }}"

    - name: Push an image "{{ acr_server_registry }}/cp2/httpd:{{ tag_image }}"
      containers.podman.podman_image:
        push: true
        name: "{{ acr_server_registry }}/cp2/httpd:{{ tag_image }}"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"
        
    - name: Push an image "{{ acr_server_registry }}/cp2/mysql:{{ tag_image }}"
      containers.podman.podman_image:
        push: true
        name: "{{ acr_server_registry }}/cp2/mysql:{{ tag_image }}"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"

