ssh_user: azureuser
acr_username: arcIrene
acr_password: yHoztbOjh7XD1fgifqzjQxS9Y9e0LgQsrdUVQ6Ophk+ACRCGNIA2
acr_server_registry: arcirene.azurecr.io
vm_public_ip: 52.151.18.242
tag_image: casopractico2

